### ISSUE TITLE
Why bower only?

### ISSUE THREAD

**Issue by 0x00000001A** [marvinhuebner/slick-animation#9]
I'm just wondering, why you're not published this plugin to the npmjs.org, but published it to the bower only?

**Comment by marvinhuebner** [comment]
When I published it on Bower, NPM wasn't that big. Today I don't have much use for the plugin anymore, so I don't know if it would make sense to publish it to NPM, because it's not really actively developed anymore.

If I have a lot of time at some point, I'd like to rewrite it, but I can't say when that is.
